apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: green
  name: green
  namespace: udacity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: configmap-vol
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: configmap-vol
          configMap:
            name: green-config
--- 
apiVersion: v1
kind: Service
metadata:
  name: green-service
  namespace: udacity
spec:
  selector:
    app: green
  ports:
    - protocol: TCP
      port: 80        # The port that the service will expose
      targetPort: 80  # The port on the pod that the service will forward traffic to
  type: LoadBalancer  # This will expose the service externally
